Repository spotinst/terraform-provider-spotinst, pull requests merged in 2019-04, with the labels that each got.

#45 [fix] dependency import
  spotinst/elastigroup_gcp_launch_configuration/fields_spotinst_elastigroup_gcp_launch_configuration.go
  vendor/vendor.json
Labels: dependencies, size/XS

#46 [fix] base64-encoded string handling/tests
  CHANGELOG.md
  spotinst/elastigroup_aws_launch_configuration/fields_spotinst_elastigroup_aws_launch_configuration.go
  spotinst/elastigroup_azure_launch_configuration/fields_spotinst_elastigroup_azure_launch_configuration.go
  spotinst/elastigroup_gcp_launch_configuration/fields_spotinst_elastigroup_gcp_launch_configuration.go
  spotinst/ocean_aws_launch_configuration/fields_spotinst_ocean_aws_launch_configuration.go
  spotinst/resource_spotinst_elastigroup_aws_test.go
Labels: size/M

#48 [fix] base64 PR additions
  spotinst/elastigroup_azure_launch_configuration/fields_spotinst_elastigroup_azure_launch_configuration.go
  spotinst/elastigroup_gcp_launch_configuration/fields_spotinst_elastigroup_gcp_launch_configuration.go
  spotinst/ocean_aws_launch_configuration/fields_spotinst_ocean_aws_launch_configuration.go
  spotinst/resource_spotinst_elastigroup_azure_test.go
  spotinst/resource_spotinst_elastigroup_gcp_test.go
  spotinst/resource_spotinst_ocean_aws_test.go
Labels: size/M

#53 v1.13.0
  .drone.yml
  CHANGELOG.md
  go.mod
  go.sum
  spotinst/ocean_aws_launch_configuration/consts.go
  spotinst/ocean_aws_launch_configuration/fields_spotinst_ocean_aws_launch_configuration.go
  spotinst/ocean_aws_launch_spec/consts.go
  spotinst/ocean_aws_launch_spec/fields_spotinst_ocean_aws_launch_spec.go
  spotinst/resource_spotinst_elastigroup_aws_beanstalk_test.go
  spotinst/resource_spotinst_ocean_aws_launch_spec_test.go
  spotinst/resource_spotinst_ocean_aws_test.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/launch_spec.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
  version/version.go
  website/docs/r/ocean_aws.html.markdown
  website/docs/r/ocean_aws_launch_spec.html.markdown
Labels: dependencies, documentation, size/XL

#54 v1.13.1, bringing up-to-date with upstream
  CHANGELOG.md
  go.mod
  go.sum
  spotinst/ocean_aws/consts.go
  spotinst/ocean_aws/fields_spotinst_ocean_aws.go
  spotinst/resource_spotinst_ocean_aws.go
  spotinst/resource_spotinst_ocean_aws_test.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/aws/aws.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/launch_spec.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/service.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
  version/version.go
  website/docs/r/ocean_aws.html.markdown
Labels: dependencies, documentation, size/XL
