Repository spotinst/terraform-provider-spotinst, pull requests merged in 2019-01, with the labels that each got.

#25 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  README.md
  spotinst/elastigroup_aws/fields_spotinst_elastigroup_aws.go
  spotinst/elastigroup_block_devices/fields_spotinst_elastigroup_block_devices.go
  spotinst/elastigroup_instance_types/fields_spotinst_elastigroup_instance_types.go
  spotinst/elastigroup_integrations/fields_spotinst_elastigroup_integrations_codedeploy.go
  spotinst/elastigroup_integrations/fields_spotinst_elastigroup_integrations_ecs.go
  spotinst/elastigroup_integrations/fields_spotinst_elastigroup_integrations_gitlab.go
  spotinst/elastigroup_integrations/fields_spotinst_elastigroup_integrations_kubernetes.go
  spotinst/elastigroup_integrations/fields_spotinst_elastigroup_integrations_mesosphere.go
  spotinst/elastigroup_integrations/fields_spotinst_elastigroup_integrations_multai_runtime.go
  spotinst/elastigroup_integrations/fields_spotinst_elastigroup_integrations_nomad.go
  spotinst/elastigroup_integrations/fields_spotinst_elastigroup_integrations_rancher.go
  spotinst/elastigroup_network_interface/fields_spotinst_elastigroup_network_interface.go
  spotinst/elastigroup_scaling_policies/fields_spotinst_elastigroup_scaling_policies.go
  spotinst/elastigroup_scheduled_task/fields_spotinst_elastigroup_scheduled_task.go
  spotinst/elastigroup_stateful/fields_spotinst_elastigroup_stateful.go
  spotinst/provider.go
Labels: size/L

#27 Make resource_limits field optional
  .travis.yml
  spotinst/commons/common_elastigroup_azure.go
  spotinst/commons/consts.go
  spotinst/elastigroup_azure_scheduled_task/consts.go
  spotinst/elastigroup_azure_scheduled_task/fields_spotinst_elastigroup_azure_scheduled_task.go
  spotinst/ocean_aws_auto_scaling/fields_spotinst_ocean_aws_auto_scaling.go
  spotinst/resource_spotinst_elastigroup_azure.go
  spotinst/resource_spotinst_elastigroup_azure_test.go
  spotinst/resource_spotinst_subscription_test.go.text
Labels: size/XL

#28 [src] Release 1.6.0
  .travis.yml
  CHANGELOG.md
Labels: size/XS

#31 [src] Improve ocean test stability
  spotinst/resource_spotinst_ocean_aws_test.go
Labels: size/M
