Repository spotinst/terraform-provider-spotinst, pull requests merged in 2020-08, with the labels that each got.

#97 Release v1.21.0
  CHANGELOG.md
  go.mod
  go.sum
  spotinst/ocean_aws_launch_spec/consts.go
  spotinst/ocean_aws_launch_spec/fields_spotinst_ocean_aws_launch_spec.go
  spotinst/resource_spotinst_ocean_aws_launch_spec_test.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/launch_spec.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
  version/version.go
  website/docs/r/ocean_aws_launch_spec.html.markdown
Labels: dependencies, documentation, size/XL

#98 Release v1.0.22
  CHANGELOG.md
  go.mod
  go.sum
  spotinst/commons/managed_instance_aws_integrations/consts.go
  spotinst/commons/managed_instance_aws_integrations/managed_instance_aws_integrations_route53.go
  spotinst/elastigroup_aws_integrations/consts.go
  spotinst/elastigroup_aws_integrations/fields_spotinst_elastigroup_aws_integrations.go
  spotinst/elastigroup_aws_integrations/fields_spotinst_elastigroup_aws_integrations_ecs.go
  spotinst/elastigroup_aws_integrations/fields_spotinst_elastigroup_aws_integrations_route53.go
  spotinst/ocean_ecs_autoscaler/fields_spotinst_ocean_ecs_autoscaler.go
  spotinst/resource_spotinst_elastigroup_aws_test.go
  spotinst/resource_spotinst_managed_instance_aws_test.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/aws/aws.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/managedinstance/providers/aws/aws.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/ocean.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/ocean_ecs.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/service.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
  version/version.go
  website/docs/r/elastigroup_aws.html.markdown
  website/docs/r/managed_instance_aws.html.markdown
  website/docs/r/multai_balancer.html.markdown
  website/docs/r/multai_deployment.html.markdown
  website/docs/r/multai_listener.html.markdown
  website/docs/r/multai_routing_rule.html.markdown
  website/docs/r/multai_target.html.markdown
  website/docs/r/multai_target_set.html.markdown
Labels: dependencies, documentation, size/XXL

#96 Fixed reference to autoscale_is_auto_config
  website/docs/r/ocean_aws.html.markdown
Labels: documentation, size/XS

#99 Release v1.23.0
  CHANGELOG.md
  go.mod
  go.sum
  spotinst/health_check/consts.go
  spotinst/health_check/fields_health_check.go
  spotinst/ocean_aws_launch_spec/consts.go
  spotinst/ocean_aws_launch_spec/fields_spotinst_ocean_aws_launch_spec.go
  spotinst/resource_spotinst_ocean_aws_launch_spec_test.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/ocean/providers/aws/launch_spec.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
  version/version.go
  website/docs/r/ocean_aws_launch_spec.html.markdown
Labels: dependencies, documentation, size/L

#100 Release v1.24.0
  CHANGELOG.md
  spotinst/ocean_aws_strategy/fields_spotinst_ocean_aws_strategy.go
  spotinst/ocean_gke_launch_spec_import/fields_spotinst_ocean_gke_launch_spec_import.go
  spotinst/resource_spotinst_ocean_gke_launch_spec_import.go
  version/version.go
Labels: size/XS

#101 fix instance_types typo in ocean_aws_launch_spec.html.markdown
  website/docs/r/ocean_aws_launch_spec.html.markdown
Labels: documentation, size/XS

#102 Release v1.25.0
  CHANGELOG.md
  spotinst/ocean_aws_strategy/fields_spotinst_ocean_aws_strategy.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/float.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/int.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/list.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/meta.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/network.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/strings.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/time.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/uuid.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/validation/web.go
  vendor/modules.txt
  version/version.go
Labels: dependencies, size/XXL
