Repository spotinst/terraform-provider-spotinst, pull requests merged in 2020-06, with the labels that each got.

#88 Support feature flags
  go.mod
  go.sum
  spotinst/commons/consts.go
  spotinst/config.go
  spotinst/provider.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/config.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/credentials/credentials.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/credentials/provider.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/credentials/provider_chain.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/credentials/provider_env.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/credentials/provider_file.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/credentials/provider_static.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/featureflag/featureflag.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/featureflag/features.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/XL

#89 Release v1.18.0
  CHANGELOG.md
  spotinst/elastigroup_aws_integrations/fields_spotinst_elastigroup_aws_integrations_nomad.go
  spotinst/resource_spotinst_elastigroup_aws_test.go
  version/version.go
  website/docs/r/elastigroup_aws.html.markdown
Labels: documentation, size/M

#92 Release v1.19.0
  CHANGELOG.md
  go.mod
  go.sum
  spotinst/elastigroup_aws_scaling_policies/consts.go
  spotinst/elastigroup_aws_scaling_policies/fields_spotinst_elastigroup_aws_scaling_policies.go
  spotinst/resource_spotinst_elastigroup_aws_test.go
  vendor/github.com/spotinst/spotinst-sdk-go/service/elastigroup/providers/aws/aws.go
  vendor/github.com/spotinst/spotinst-sdk-go/spotinst/version.go
  vendor/modules.txt
  version/version.go
  website/docs/r/elastigroup_aws.html.markdown
Labels: dependencies, documentation, size/L
